version: "3.5" #TODO

services:
  bcc-node-ogmios:
    image: tbco/bcc-node-ogmios:v4.1.0-${NETWORK:-mainnet}
    logging:
      driver: "json-file"
      options:
        max-size: "400k"
        max-file: "20"
    ports:
      - ${OGMIOS_PORT:-1337}:1337
    restart: on-failure
    volumes:
      - node-db:/db

volumes:
  node-db:
