import Transaction, { TransactionInput, TransactionOutput } from './Transaction'
import { Wallet } from './Wallet'
import { Provider, ProviderType, BccProvider, WalletProvider } from './Provider'
import * as Utils from './Utils'
import { InMemoryKeyManager, LedgerKeyManager, RustBcc, ClientHttpProvider, BccWalletProvider } from './lib'
import { FeeAlgorithm, ChainSettings } from './Bcc'

export default function BccSDK (bcc = RustBcc) {
  return {
    Transaction (inputs: TransactionInput[], outputs: TransactionOutput[], feeAlgorithm = FeeAlgorithm.default) {
      return Transaction(bcc, inputs, outputs, feeAlgorithm)
    },
    InMemoryKeyManager (keyArgs: { password: string, accountIndex?: number, mnemonic: string }) {
      return InMemoryKeyManager(bcc, keyArgs)
    },
    LedgerKeyManager,
    Utils: {
      generateMnemonic: Utils.generateMnemonic,
      addressDiscoveryWithinBounds: (addressDiscoveryArgs: Utils.AddressDiscoveryArgs, chainSettings = ChainSettings.mainnet) => {
        return Utils.addressDiscoveryWithinBounds(bcc, addressDiscoveryArgs, chainSettings)
      },
      verifyMessage: bcc.verifyMessage
    },
    connect (provider: Provider) {
      const clientConnection = {
        wallet: Wallet(bcc, provider),
        submitTransaction: (<BccProvider>provider).submitTransaction,
        createWallet: () => { throw new Error('Unsupported client connection operation. Create a new key with the KeyManager instead.') },
        listWallets: () => { throw new Error('Unsupported client connection operation. Keys generated by the client are not persisted.') }
      }

      const remoteConnection = {
        wallet: Wallet(bcc, provider),
        submitTransaction: () => { throw new Error('Unsupported remote connection operation. Use the createAndSignTransaction method on the Wallet interface instead') },
        createWallet: (<WalletProvider>provider).createWallet,
        listWallets: (<WalletProvider>provider).wallets
      }

      return provider.type === ProviderType.bcc ? clientConnection : remoteConnection
    }
  }
}

export { RustBcc, ClientHttpProvider, BccWalletProvider }
